### ISSUE TITLE
Process view: Process objects are not removed properly, they disappear in GUI but JSON objects are still sent.

### ISSUE THREAD

**Issue by tm11ajn** [genomizer/genomizer-web#108]
Recreate bug:
1. Create rawToProfile process.
2. Add row and enter data.
3. Create new rawToProfile process.
4. Add row and enter data.
5. Remove any of the two.
6. Press "Process".

**Comment by azoimide** [comment]
@tm11ajn @luddward Is this merged into develop?

**Comment by tm11ajn** [comment]
Yeah, the bug is, that is, if @Palledaman merged the pull request.

**Comment by Palledaman** [comment]
Done in commit 70cdce33920206d466c2380afaa13c64acfdb295

**Comment by tm11ajn** [comment]
Still needs to be fixed :)

**Comment by azoimide** [comment]
Fixed in e8b46ef
