### ISSUE TITLE
Remove Convert and Workspace

### ISSUE THREAD

**Issue by Palledaman** [genomizer/genomizer-web#117]
Delete the tab in the menu.

**Comment by tm11ajn** [comment]
I would suggest NOT deleting convert, but adding a front page to it explaining how it's done or doing something similiar to the main window for process, because otherwise we would need to delete the process tab as well for consistency.

**Comment by Palledaman** [comment]
Fixed in commit 5250ed1ab8b2f074efddf772b44017f2e4d0e604
