### ISSUE TITLE
File upload fields are reset on new file

### ISSUE THREAD

**Issue by tastyburger** [genomizer/genomizer-web#54]
When `Select files to upload` is pressed and an additional file is selected for upload, the fields `Author` and `Metadata` are reset for the currently selected files. Could be a problem if a user selects perhaps 10 files, fills in all information, then wants to add another file before uploading and finds out that all input is wiped.

Issue experienced using Iceweasel 31.6.0.

**Comment by Palledaman** [comment]
Now it works on develop-branch.

**Comment by tastyburger** [comment]
Fields are still reset but this time to some default values. This happens even when a file is deselected for upload.
