### ISSUE TITLE
Message timeout

### ISSUE THREAD

**Issue by tastyburger** [genomizer/genomizer-web#64]
The messages that are displayed in the middle of the screen do not automatically timeout. They have to be removed manually. But this applies only to the latest message, older ones seem to get removed.

**Comment by Palledaman** [comment]
Works now.

**Comment by tastyburger** [comment]
Where is the fix located?

**Comment by Palledaman** [comment]
commit e216d6f93f56099a7abd224fe5ab0471704ce0d9
